title: Go on before complaining
description: Write stories how to deal with issues, builds up something, etc.
theme: just-the-docs

url: https://s-bak.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
